In [2]:
import pandas as pd 
import numpy as np
import json 
import pdb 
from tqdm import tqdm 


In [4]:
R1_prediction = pd.read_csv('test_prediction_rule1.csv', index_col=None)
R2_prediction = pd.read_csv('test_prediction_rule2.csv', index_col=None)

In [5]:
R1_prediction.columns

Index(['predict', 'predict.1', 'predict.2'], dtype='object')

In [6]:
Pred_score = R1_prediction['predict']
Pred_score = Pred_score[1:]

cid= R1_prediction['predict.1'][1:]
Prot_Id  = R1_prediction['predict.2'][1:]


Pred_score_R2 = R2_prediction['predict'][1:]
cid_r2= R2_prediction['predict.1'][1:]
Prot_Id_r2  = R2_prediction['predict.2'][1:]



In [7]:
Pred_score.max()

'0.9979187250137329'

In [8]:
Pred_score_R2.max()

'0.9961950778961182'

In [9]:
Pred_score_ar = Pred_score.to_numpy()
Pred_score_ar = Pred_score_ar.astype(float)

Pred_score_ar2 = Pred_score_R2.to_numpy()
Pred_score_ar2 = Pred_score_ar2.astype(float)


In [10]:
indices = np.where(Pred_score == Pred_score.max())

In [11]:
indices[0][0]

1524

In [12]:
Prot_Id[indices[0][0]]

'A0A7T5END7'

In [15]:
indices = (-Pred_score_ar).argsort()[:10]
indices2 = (-Pred_score_ar2).argsort()[:10]


In [17]:
indices2

array([2901, 2428, 2850, 2868, 1477, 2842, 1979, 2872, 1420, 1754])

In [18]:
indices

array([1524, 1341, 1808,  967, 1467, 1440, 1655, 1560, 1811,  206])

In [19]:
prot_id_ar = Prot_Id.to_numpy()
prot_id_ar2 = Prot_Id_r2.to_numpy()


## Rule 1

In [20]:
prot_id_ar[indices]

array(['A0A7T5EPK7', 'STHU_49550', 'A0A517XRJ4', 'A0A1P8FJN2',
       'IRT44_14895', 'Q9KDZ1', 'M271_48535', 'A0A5C0SAA6', 'Q028N1',
       'D8MLI7'], dtype=object)

In [21]:
Pred_score_ar[indices]

array([0.99791873, 0.99734288, 0.99705887, 0.9970237 , 0.99694508,
       0.99686539, 0.99683475, 0.99681675, 0.99679601, 0.99675852])

## Rule 2

In [22]:
prot_id_ar2[indices2]

array(['A0A1D8PAW7', 'A0A410E1I1', 'A0A5B5UC26', 'A0A0H4PM96',
       'A0A2Z6E2T0', 'I3YKZ3', 'AMK02_PA00059', 'A0A142ENP5', 'E2LZJ5',
       'A0A1D7TLV7'], dtype=object)

In [23]:
Pred_score_ar2[indices2]

array([0.99619508, 0.99379802, 0.99307263, 0.99273336, 0.99266869,
       0.99225652, 0.99192488, 0.99155545, 0.99140382, 0.99131525])

In [24]:
len(Pred_score_ar2)

2994

In [25]:
len(Pred_score)

2819